<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Soenneker.Librarian.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moq" Version="4.21.0" />
        <PackageReference Include="TUnit" Version="1.72.16" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Soenneker.Librarian.LocalStorage/Soenneker.Librarian.LocalStorage.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.SessionStorage/Soenneker.Librarian.SessionStorage.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.IndexedDb/Soenneker.Librarian.IndexedDb.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.Maui.Secure/Soenneker.Librarian.Maui.Secure.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.Generators/Soenneker.Librarian.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="../../src/Soenneker.Librarian.CouchDb/Soenneker.Librarian.CouchDb.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.Kv/Soenneker.Librarian.Kv.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.D1/Soenneker.Librarian.D1.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.AzureBlob/Soenneker.Librarian.AzureBlob.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.R2/Soenneker.Librarian.R2.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.Abstractions/Soenneker.Librarian.Abstractions.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.Core/Soenneker.Librarian.Core.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.Memory/Soenneker.Librarian.Memory.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.FileSystem/Soenneker.Librarian.FileSystem.csproj" />
        <ProjectReference Include="../../src/Soenneker.Librarian.Redis/Soenneker.Librarian.Redis.csproj" />
        <ProjectReference Include="..\..\src\Soenneker.Librarian.Postgres\Soenneker.Librarian.Postgres.csproj" />
        <ProjectReference Include="..\..\src\Soenneker.Librarian.Mongo\Soenneker.Librarian.Mongo.csproj" />
        <ProjectReference Include="..\..\src\Soenneker.Librarian.Cosmos\Soenneker.Librarian.Cosmos.csproj" />
    </ItemGroup>

</Project>
