<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Soenneker.Librarian.Memory/Soenneker.Librarian.Memory.csproj" />
    <ProjectReference Include="../../src/Soenneker.Librarian.FileSystem/Soenneker.Librarian.FileSystem.csproj" />
    <ProjectReference Include="../../src/Soenneker.Librarian.Redis/Soenneker.Librarian.Redis.csproj" />
    <ProjectReference Include="../../src/Soenneker.Librarian.Postgres/Soenneker.Librarian.Postgres.csproj" />
  </ItemGroup>
</Project>
