using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Soenneker.Librarian.Generators;

[Generator]
public sealed class LibrarianGenerator : IIncrementalGenerator
{
    private const string QueryAttribute = "Soenneker.Librarian.Abstractions.Queries.GenerateLibrarianQueriesAttribute";

    private static readonly DiagnosticDescriptor UnsupportedModel = new("LIBGEN001", "Model cannot be generated",
        "Librarian cannot generate metadata for '{0}': use a non-generic, accessible type", "Librarian",
        DiagnosticSeverity.Warning, true);

    private static readonly DiagnosticDescriptor RuntimeQuery = new("LIBGEN002", "Query uses runtime execution",
        "Librarian query delegate was not generated: {0}. The existing runtime path remains active.", "Librarian",
        DiagnosticSeverity.Warning, true);
    private static readonly DiagnosticDescriptor AutomaticRuntimeQuery = new("LIBGEN002", "Query uses runtime execution",
        "Librarian query delegate was not generated: {0}. The existing runtime path remains active.", "Librarian",
        DiagnosticSeverity.Info, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Soenneker.Librarian.Abstractions.Queries.LibrarianModelAttribute",
            static (node, _) => node is TypeDeclarationSyntax, static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);
        var discoveredModels = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is InvocationExpressionSyntax,
            static (ctx, _) => QueryDiscovery.DocumentType(ctx)).Where(static type => type is not null)
            .Select(static (type, _) => type!);
        var allModels = models.Collect().Combine(discoveredModels.Collect()).Select(static (input, _) => input.Left.AddRange(input.Right));
        context.RegisterSourceOutput(allModels.Combine(context.CompilationProvider), static (output, input) =>
        {
            var types = input.Left;
            var text = new StringBuilder(
                "// <auto-generated/>\n#nullable enable\nnamespace Soenneker.Librarian.Generated;\ninternal static class LibrarianModels\n{\n[global::System.Runtime.CompilerServices.ModuleInitializer]\ninternal static void Register()\n{\n");
            foreach (INamedTypeSymbol type in types.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default))
            {
                if (!Accessible(type) || type.IsGenericType)
                {
                    if (type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "Soenneker.Librarian.Abstractions.Queries.LibrarianModelAttribute"))
                        output.ReportDiagnostic(Diagnostic.Create(UnsupportedModel, type.Locations.FirstOrDefault(), type.Name));
                    continue;
                }

                var seen = new HashSet<string>(StringComparer.Ordinal);
                for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType)
                    foreach (ISymbol member in current.GetMembers())
                    {
                        if (member.IsStatic || !seen.Add(member.Name))
                            continue;
                        ITypeSymbol? valueType = member switch
                        {
                            IPropertySymbol
                            {
                                IsIndexer: false, GetMethod.DeclaredAccessibility: Accessibility.Public
                            } p => p.Type,
                            IFieldSymbol
                            {
                                DeclaredAccessibility: Accessibility.Public, IsImplicitlyDeclared: false
                            } f => f.Type,
                            _ => null
                        };
                        if (valueType is null || !Accessible(valueType) || valueType.IsRefLikeType ||
                            valueType.TypeKind == TypeKind.Pointer)
                            continue;
                        string? jsonName = member.GetAttributes()
                                                 .FirstOrDefault(a =>
                                                     a.AttributeClass?.ToDisplayString() ==
                                                     "System.Text.Json.Serialization.JsonPropertyNameAttribute")
                                                 ?.ConstructorArguments.FirstOrDefault().Value as string;
                        bool auto = member is IPropertySymbol { IsVirtual: false, IsOverride: false } property &&
                                    (property.GetMethod?.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "System.Runtime.CompilerServices.CompilerGeneratedAttribute") == true ||
                                    property.DeclaringSyntaxReferences.Any(r =>
                                        r.GetSyntax() is PropertyDeclarationSyntax
                                        {
                                            ExpressionBody: null, AccessorList: { } accessors
                                        } && accessors.Accessors.All(a =>
                                            a.Body is null && a.ExpressionBody is null)));
                        bool index = auto && valueType.SpecialType is SpecialType.System_Int32
                            or SpecialType.System_Int64 or SpecialType.System_Decimal or SpecialType.System_String
                            or SpecialType.System_Boolean;
                        text.Append("global::Soenneker.Librarian.Abstractions.Queries.GeneratedQueryMetadata.Register<")
                            .Append(Name(type)).Append(", ").Append(Name(valueType)).Append(">(")
                            .Append(Literal(member.Name)).Append(", ")
                            .Append(jsonName is null
                                ? "global::System.Text.Json.JsonNamingPolicy.CamelCase.ConvertName(" +
                                  Literal(member.Name) + ")"
                                : Literal(jsonName)).Append(", static value => value.@").Append(member.Name)
                            .Append(", ").Append(index ? "true" : "false")
                            .Append(IndexFactory(member, valueType, index)).Append(");\n");
                        // Expression members on inherited properties refer to the declaring type.
                        if (!SymbolEqualityComparer.Default.Equals(type, current) && Accessible(current) &&
                            !current.IsGenericType)
                            text
                                .Append(
                                    "global::Soenneker.Librarian.Abstractions.Queries.GeneratedQueryMetadata.Register<")
                                .Append(Name(current)).Append(", ").Append(Name(valueType)).Append(">(")
                                .Append(Literal(member.Name)).Append(", ")
                                .Append(jsonName is null
                                    ? "global::System.Text.Json.JsonNamingPolicy.CamelCase.ConvertName(" +
                                      Literal(member.Name) + ")"
                                    : Literal(jsonName)).Append(", static value => value.@").Append(member.Name)
                                .Append(", ").Append(index ? "true" : "false")
                                .Append(IndexFactory(member, valueType, index)).Append(");\n");
                    }
            }

            text.Append("}\n");
            if (input.Right.GetTypeByMetadataName("Soenneker.Librarian.Mongo.MongoJsonSerializerRegistry") is not null)
                text.Append(MongoRegistrationEmitter.Emit(types, output));
            text.Append("}\n");
            output.AddSource("LibrarianModels.g.cs", text.ToString());
        });

        var calls = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is InvocationExpressionSyntax { ArgumentList.Arguments.Count: > 0 },
            static (ctx, _) => GetCall(ctx)).Where(static call => call is not null);
        context.RegisterSourceOutput(calls.Collect(), static (output, calls) =>
        {
            var text = new StringBuilder(
                "// <auto-generated/>\n#nullable enable\nnamespace System.Runtime.CompilerServices { [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)] file sealed class InterceptsLocationAttribute : global::System.Attribute { public InterceptsLocationAttribute(int version, string data) {} } }\nnamespace Soenneker.Librarian.Generated { internal static class LibrarianQueryInterceptors {\n");
            int index = 0;
            foreach (GeneratedCall? call in calls)
            {
                if (call!.Error is not null)
                {
                    output.ReportDiagnostic(Diagnostic.Create(call.Explicit ? RuntimeQuery : AutomaticRuntimeQuery, call.Location, call.Error));
                    continue;
                }

                text.Append(call.Source!.Replace("__INTERCEPTOR__", "Query" + index++));
            }

            text.Append("} }\n");
            if (index > 0)
                output.AddSource("LibrarianQueryInterceptors.g.cs", text.ToString());
        });
    }

    private static GeneratedCall? GetCall(GeneratorSyntaxContext context)
    {
        var syntax = (InvocationExpressionSyntax)context.Node;
        SemanticModel model = context.SemanticModel;
        if (model.GetSymbolInfo(syntax).Symbol is not IMethodSymbol method ||
            method.ContainingType.ToDisplayString() != "System.Linq.Queryable")
            return null;
        bool optedIn = syntax.Ancestors().OfType<TypeDeclarationSyntax>().Any(t =>
            model.GetDeclaredSymbol(t)?.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == QueryAttribute) == true);
        if (!optedIn && !QueryDiscovery.IsLibrarian(QueryDiscovery.Source(syntax, method), model)) return null;
        GeneratedCall Fallback(string error) => new(syntax.GetLocation(), error, null, optedIn);
        IMethodSymbol original = method.ReducedFrom ?? method;
        if (original.Parameters.Length != 2)
            return null;
        if (original.Parameters[1].Type is not INamedTypeSymbol parameterType ||
            parameterType.OriginalDefinition.ToDisplayString() != "System.Linq.Expressions.Expression<TDelegate>")
            return null;
        if (method.TypeArguments.Any(t => !Accessible(t)))
            return Fallback("generic, anonymous, or inaccessible query types are not supported yet");
        // Paging has no expression delegate to generate.
        if (method.Name is "Take" or "Skip")
            return null;
        string parameterName = original.Parameters[1].Name;
        ArgumentSyntax argument = syntax.ArgumentList.Arguments.FirstOrDefault(a => a.NameColon?.Name.Identifier.ValueText == parameterName)
            ?? syntax.ArgumentList.Arguments.Last();
        if (argument.Expression is not LambdaExpressionSyntax lambda)
            return Fallback("the lambda must be available at this call site");
        if (lambda.Ancestors().Any(n => n is CheckedStatementSyntax or CheckedExpressionSyntax))
            return Fallback("the enclosing checked context requires runtime execution");
        if (model.GetTypeInfo(lambda).ConvertedType is not INamedTypeSymbol
            {
                TypeArguments.Length: 1
            } expressionType || expressionType.TypeArguments[0] is not INamedTypeSymbol
            {
                DelegateInvokeMethod: { Parameters.Length: 1 } invoke
            } delegateType)
            return Fallback("only single-parameter lambdas are supported");
        var rewriter = new QueryLambdaRewriter(model, lambda);
        string rewritten = rewriter.Visit(lambda)!.NormalizeWhitespace().ToFullString();
        if (rewriter.Error is not null)
            return Fallback(rewriter.Error);
#pragma warning disable RSEXPERIMENTAL002
        var location = model.GetInterceptableLocation(syntax);
#pragma warning restore RSEXPERIMENTAL002
        if (location is null)
            return Fallback("the compiler cannot intercept this call");
        string input = Name(invoke.Parameters[0].Type);
        string result = Name(invoke.ReturnType);
        string sourceType = "global::System.Linq." +
                            (method.Name.StartsWith("ThenBy", StringComparison.Ordinal)
                                ? "IOrderedQueryable"
                                : "IQueryable") + "<" + input + ">";
        string generic = method.TypeArguments.Length == 0
            ? ""
            : "<" + string.Join(", ", method.TypeArguments.Select(Name)) + ">";
        string source = "[global::System.Runtime.CompilerServices.InterceptsLocation(" + location.Version + ", " +
                        Literal(location.Data) + ")]\n" + "internal static " + Name(method.ReturnType) +
                        " __INTERCEPTOR__(this " + sourceType + " source, " + Name(expressionType) +
                        " expression)\n{\n" +
                        "global::Soenneker.Librarian.Abstractions.Queries.GeneratedQueryFunctions.Register<" + input +
                        ", " + result + ">(expression, " + rewritten + ");\n" +
                        (method.Name == "Select" ? ProjectionRegistration(model, lambda) : "") +
                        "return global::System.Linq.Queryable." + method.Name + generic + "(source, expression);\n}\n";
        return new GeneratedCall(syntax.GetLocation(), null, source);
    }

    private static string ProjectionRegistration(SemanticModel model, LambdaExpressionSyntax lambda)
    {
        if (lambda.Body is not ObjectCreationExpressionSyntax creation || creation.Initializer is not null ||
            creation.ArgumentList is null)
            return "";
        if (model.GetTypeInfo(creation).Type is not { } type || !Accessible(type))
            return "";
        var arguments = new List<string>();
        foreach (ArgumentSyntax argument in creation.ArgumentList.Arguments)
        {
            if (argument.NameColon is not null ||
                model.GetTypeInfo(argument.Expression).ConvertedType is not { } argumentType ||
                !Accessible(argumentType))
                return "";
            arguments.Add("(" + Name(argumentType) + ")values[" + arguments.Count + "]!");
        }

        return
            "global::Soenneker.Librarian.Abstractions.Queries.GeneratedQueryProjections.Register(expression.Body, static values => new " +
            Name(type) + "(" + string.Join(", ", arguments) + "));\n";
    }

    internal static string Name(ITypeSymbol type) => type.ToDisplayString(
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));

    private static string IndexFactory(ISymbol member, ITypeSymbol type, bool supported)
    {
        if (!supported)
            return "";
        string access = "value.@" + member.Name;
        string arguments = type.SpecialType switch
        {
            SpecialType.System_String => access + " is null ? 0 : 3, Text: " + access,
            SpecialType.System_Boolean => "1, " + access + " ? 1m : 0m",
            _ => "2, " + access
        };
        return ", static value => new global::Soenneker.Librarian.Abstractions.Queries.GeneratedIndexKey(" + arguments +
               ")";
    }

    internal static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);

    internal static bool Accessible(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array)
            return Accessible(array.ElementType);
        if (type is ITypeParameterSymbol || type.TypeKind is TypeKind.Error or TypeKind.Pointer || type.IsRefLikeType)
            return false;
        for (ISymbol? current = type; current is INamedTypeSymbol; current = current.ContainingType)
            if (current.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal) ||
                current is INamedTypeSymbol { IsFileLocal: true })
                return false;
        return type is not INamedTypeSymbol named || !named.IsAnonymousType && named.TypeArguments.All(Accessible);
    }
}
